version: "3.4"

services:
  db:
    build: ./sqlserver
    container_name: "fibonacci_db"
    platform: linux/arm64/v8
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"